package br.com.ricardo.vagaradar.entity;

public enum MotivoRejeicao {
    INGLES_AVANCADO,
    SENIORIDADE,
    REQUISITOS_EXCESSIVOS,
    TECNOLOGIAS,
    LOCALIZACAO,
    MODELO_TRABALHO,
    SALARIO,
    TIPO_CONTRATO,
    AREA_ATUACAO,
    EMPRESA,
    BENEFICIOS,
    CARGA_HORARIA,
    VAGA_NAO_CLARA,
    VAGA_DUPLICADA,
    OUTRO
}
